### ISSUE TITLE
Who creates lock record in "wait" case?

### ISSUE THREAD

**Issue by funny-falcon** [zieckey/etcdsync#1]
https://github.com/zieckey/go-etcd-lock/blob/master/mutex.go#L135 - who creates lock record here?

Perhaps I'm missing something with etcd api and semantic.

**Comment by zieckey** [comment]
Thanks for your opinion. I have updated the code. Please review again.

**Comment by funny-falcon** [comment]
Looks like you didn't `git push`

**Comment by zieckey** [comment]
Sorry, I do `git push` all code. I am confused. What's your suggestion?

**Comment by funny-falcon** [comment]
Then I could not understand: code didn't changed since the time I opened the issue.
https://github.com/zieckey/etcdsync/blob/master/mutex.go#L133-L136

``` go
        m.debug("Received an event : %q", resp)
        if resp.Action == deleteAction || resp.Action == expireAction {
            return nil
        }
```

and then https://github.com/zieckey/etcdsync/blob/master/mutex.go#L82-L84

``` go
        if m.lock() == nil {
            return nil
        }
```

More over: there is no way for `(*etcdsync.Mutex).Lock()` to return `err != nil` - err is never assigned.

**Comment by zieckey** [comment]
Thanks a lot. I updated the code https://github.com/zieckey/etcdsync/blob/master/mutex.go#L82  to fix 
`(*etcdsync.Mutex).Lock()` which never returns an error.

``` go
        err = m.lock()
        if err == nil {
            return nil
        }
```

And then, I still don't get what you mean about https://github.com/zieckey/etcdsync/blob/master/mutex.go#L134-L137 ?

``` go
        m.debug("Received an event : %q", resp)
        if resp.Action == deleteAction || resp.Action == expireAction {
            return nil
        }
```

**Comment by funny-falcon** [comment]
On a good part you creates key in etcd. If key already existed, you setup watcher and wait till key is deleted... and do not create key.

So, one way you create key, other way you don't. Why?

**Comment by zieckey** [comment]
OK, I got it. Thanks. That's a logic error. I have fixed it and add test case to cover it. 
Thanks a lot, again.

**Comment by zieckey** [comment]
Thanks.
