### ISSUE TITLE
failing go get github.com/zieckey/etcdsync

### ISSUE THREAD

**Issue by luedigernet** [zieckey/etcdsync#2]
go get github.com/zieckey/etcdsync fails with following error messages.

<snip>
package github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context: cannot find package "github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context" in any of:
    /usr/local/go/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context (from $GOROOT)
    /Users/rl/Dev/gocode/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context (from $GOPATH)
</snip>

**Comment by zieckey** [comment]
I have changed the code 'github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context' to 'golang.org/x/net/context'.
Please try again.

**Comment by luedigernet** [comment]
Thumbs up now it works. Thx for the super fast reaction
