### ISSUE TITLE
Why ignoring errors ?

### ISSUE THREAD

**Issue by ghost** [zieckey/etcdsync#4]
I don't understand why you ignore errors in **New** function https://github.com/zieckey/etcdsync/blob/master/mutex.go#L45
I think it would be better to return error in New function with Mutex:

func New(key string, ttl int, machines []string) *Mutex, error

**Comment by zieckey** [comment]
Yes, your suggest makes sense. Welcome to open a PR. Thanks

**Comment by ghost** [comment]
Done.
https://github.com/zieckey/etcdsync/pull/5

**Comment by ghost** [comment]
up!

**Comment by ghost** [comment]
Sorry, forgot to update readme and example.go. Shall I send another pull request, or you fix it by yourself ?

**Comment by zieckey** [comment]
I have fixed it. Thanks for your contribution.
